### ISSUE TITLE
Add SSE example

### ISSUE THREAD

**Issue by muka** [modelcontextprotocol/typescript-sdk#106]
**Is your feature request related to a problem? Please describe.**
For starters an example with SSE would be useful

**Describe the solution you'd like**
I would suggest to refer to existing community contribution to create a simple example 
https://github.com/tzolov/mcp-everything-server-docker-image/blob/main/everything/sse.ts

I am not confident enough to create a PR myself with some reference code, however this one works

Thank you

**Comment by punkpeye** [comment]
You can reference SSE implementation here https://github.com/punkpeye/fastmcp

**Comment by muka** [comment]
Hi @punkpeye  thank you, very good project.

I got playing and a working setup also here (using your fastmcp as a baseline), the main difference in the approach is that I handled the MCP server all over one single HTTP server. 

https://github.com/muka/agents-test/blob/main/src/mcp/mcp-proxy.ts

Maybe the same could be supported in fastmcp ?

**Comment by punkpeye** [comment]
> the main difference in the approach is that I handled the MCP server all over one single HTTP server.

I am trying to understand what do you mean by this, but cannot wrap my head around it. FastMCP also uses a single HTTP server. Can you try to rephrase? Do you mean like re-using the server for other use cases beyond SSE?

**Comment by muka** [comment]
Sure, what I mean is to handle multiple MCP server instances under a single http server eg. `/mcp1` `/mcp2` `/mcpX`

Relevant line of code to explain me better https://github.com/muka/agents-test/blob/main/src/mcp/mcp-proxy.ts#L80

The motivation is that there are many MCP server around which are interesting however those may use stdio or python. Using a sort of proxy would be useful for the sake of normalizing client interactions and possibly have a catalog of available MCP capabilities.

EDIT: I think I have been overlooking at this and mixed up different things. There are options out there e.g. https://github.com/adamwattis/mcp-proxy-server

Your project is a great tool to build MCP in typescript. Thanks!
