### ISSUE TITLE
Cannot find module '@modelcontextprotocol/sdk/client' or its corresponding type declarations

### ISSUE THREAD

**Issue by rtuin** [modelcontextprotocol/typescript-sdk#67]
I'm getting this error on a very basic Client implementation of `@modelcontextprotocol/sdk` on node 20 and 22.

Reproduction script:

```typescript
import { Client } from '@modelcontextprotocol/sdk/client';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio';
import { ListResourcesResultSchema } from '@modelcontextprotocol/sdk/types';

const run = async () => {
  const transport = new StdioClientTransport({
    command: 'npx @modelcontextprotocol/postgres-server postgres://....',
  });

  const client = new Client(
    {
      name: 'example-client',
      version: '1.0.0',
    },
    { capabilities: {} }
  );

  await client.connect(transport);

  const resources = await client.request({ method: 'resources/list' }, ListResourcesResultSchema);
  console.log(resources);
};

run();
```

Is this a known issue? Any thoughts on how to get this example working?

**Comment by jspahrsummers** [comment]
The MCP library exports only ESM modules, which have to be imported with their file extensions, like:

```typescript
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
```

Does that work for you?

_Separately, note that this won't work—you'll have to move everything after `npx` here to `args`:_
```typescript
command: 'npx @modelcontextprotocol/postgres-server postgres://....',
```

**Comment by tyre** [comment]
I was also banging my head against this last night. Why does the example in the README show normal package imports while it only works (at least for me locally) when digging into the library for the specific file?

**Comment by rtuin** [comment]
> The MCP library exports only ESM modules, which have to be imported with their file extensions, like:
> 
> ```ts
> import { Client } from '@modelcontextprotocol/sdk/client/index.js';
> ```
> 
> Does that work for you?

Yes, that's it, thanks.
I've [updated the docs accordingly](https://github.com/modelcontextprotocol/typescript-sdk/pull/69).
