### ISSUE TITLE
Follow the official weather-server tutorial, but it doesn't work.

### ISSUE THREAD

**Issue by random-yang** [modelcontextprotocol/typescript-sdk#72]
Tutorial link:
https://modelcontextprotocol.io/docs/first-server/typescript#check-current-weather

Screenshot:
![Pasted Graphic 5](https://github.com/user-attachments/assets/6350f857-e7ab-4a6b-8079-e0b10de3f0e2)

**Comment by random-yang** [comment]
I figure it out, need to manually refer to the settings below:
![image](https://github.com/user-attachments/assets/5c9896ef-e138-43a9-8e71-22b9ab1b7f71)

At the beginning, the default settings are probably like this, which makes me mistakenly think that I don't need to make further settings.
![image](https://github.com/user-attachments/assets/ad7def97-ffe4-40b3-9dc0-a86725430440)

**Comment by random-yang** [comment]
The statement in README is different from that in the document. I am a bit confused.
![image](https://github.com/user-attachments/assets/9a505908-c27b-4bee-a9ce-70592b27c984)

**Comment by jspahrsummers** [comment]
Sorry, there are some discrepancies in whether it's expecting the server to be installed globally or not.

Using either the path to the _built_ server, or `node` (with the path to the built server as an argument), should work. I'll update the docs to not use `weather-server` as the command directly.

Thanks for flagging!
