### ISSUE TITLE
Provider helper to convert capabilities to tool functions

### ISSUE THREAD

**Issue by JonasHelming** [modelcontextprotocol/typescript-sdk#77]
**Is your feature request related to a problem? Please describe.**
I would like to expose MCP capabilities to an LLM supporting tool functions.
We assume, although this part is not described in the architecture, that in the Claude desktop app you gather the capabilities via MCP locally and then expose them via tool functions to the underlying LLM. The format seems literally identical (but this is of course not guaranteed). if this assumption is correct, it would be great o have this converstion step available in the SDK for mutiple LLM provider (Anthropic, OpenAi, etc.) so that adopters of MCP do not have to re-implement this.

**Describe the solution you'd like**
Add helper to convert MCP capabilities into tool functions for various LLM provider.

**Comment by jspahrsummers** [comment]
This might be a better fit for one or more small bindings libraries that sit on top of MCP. We'd like to avoid the need for any MCP SDKs to depend on different providers directly.

**Comment by JonasHelming** [comment]
@jspahrsummers That makes a lot of sense. However, I think it would be good to host this in the same org, as to my understanding, almost everybody using MCP would need this. It would be also great if you would consider publishing this exact code you used in the Anthropic desktop app. I am aware that this is almost a no op in terms of what it does. However, if formats evolve, it would be good to have this conversion encapsulated and maintained.

**Comment by jspahrsummers** [comment]
We'd really like to avoid anything in the @modelcontextprotocol org being directly coupled to any provider, as this is meant to be a community project, and we don't want uneven levels of support for different providers (e.g., as their APIs evolve over time).

**Comment by JonasHelming** [comment]
Hi,

Thank you for your thoughtful reply! I completely understand your perspective, and it's ultimately up to you to decide how to proceed. If this feature request doesn't align with your vision, please feel free to close it—I won't take it personally.

That said, I really appreciate the concept and vision of MCP. The idea of a protocol like this has enormous potential, and I think it's heading in a great direction. My perspective comes from my own use case: I'm currently integrating MCP into the Theia IDE (you can read more about it here: [[Introducing AI in the Theia IDE](https://eclipsesource.com/blogs/2024/10/08/introducting-ai-theia-ide/)](https://eclipsesource.com/blogs/2024/10/08/introducting-ai-theia-ide/)). In this context, I found that a conversation mechanism like the one I suggested is almost essential—not just for my integration, but likely for most adopters of MCP. The aim of this feature request is to reduce redundancy and avoid a situation where each adopter has to implement the same thing individually, even if it's a relatively small addition.

Regarding the concern about keeping the repository provider-neutral, I completely get where you're coming from. However, I feel there's always a balance to strike. MCP Servers already includes integrations with specific providers (e.g., GitHub, Google Maps, Google Drive, Slack), which shows that while the protocol itself remains neutral, the examples and supported integrations are somewhat opinionated. This adds value for adopters, as they can see how things work in practical, real-world scenarios. I think this is a natural trade-off for a framework like MCP: remaining neutral but also practical for adopters.

Lastly, I want to reiterate my appreciation for this project. It's an impressive initiative, and I'm excited to see where it goes! If this suggestion doesn't fit your vision, feel free to close the request—no hard feelings.

Best regards,  
Jonas
