### ISSUE TITLE
Resources, Sampling don't seem to work with Claude Desktop

### ISSUE THREAD

**Issue by martinbechard** [modelcontextprotocol/typescript-sdk#79]
**Describe the bug**
I implemented a sever with resources, tools, sampling and prompts.
I can access them all fine with the MCP inspector.
However, with Claude Desktop only the tools seem to work - what gives? 
Is there any trick to get Claude Desktop to display the available resources ? What does it do with the sampling?

The documentation makes it seem like this is all supported, but are tools the only thing supported by Claude Desktop?

**Comment by AaronAbuUsama** [comment]
i dont think sampling is supported in claude yet.

**Comment by jspahrsummers** [comment]
Correct, sampling is not supported in Claude Desktop.

Resources are supported by explicitly attaching them from the 🔌 icon.

I'm going to close this out, as this is not related to the SDK. Please open a discussion at https://github.com/orgs/modelcontextprotocol/discussions for any other questions.

**Comment by martinbechard** [comment]
Thé SDK document would be improved by clarifying what actually works with your company’s product.On Dec 2, 2024, at 8:02 AM, Justin Spahr-Summers ***@***.***> wrote:﻿
Correct, sampling is not supported in Claude Desktop.
Resources are supported by explicitly attaching them from the 🔌 icon.
I'm going to close this out, as this is not related to the SDK. Please open a discussion at https://github.com/orgs/modelcontextprotocol/discussions for any other questions.
