### ISSUE TITLE
Conceptual question - can you pipe from transport to transport?

### ISSUE THREAD

**Issue by Madd0g** [modelcontextprotocol/typescript-sdk#80]
**Is your feature request related to a problem? Please describe.**
I'm wondering if conceptually you can just hook up one transport to another since there's a known protocol, I guess my question is how hard it would be with the typescript SDK to create an MCP that just mirrors another MCP, just on a different transport

**Describe the solution you'd like**

It would be cool if it was possible, I guess.

**Comment by jspahrsummers** [comment]
This is definitely possible! https://github.com/modelcontextprotocol/typescript-sdk/issues/10 showcases an example of this sort of proxy pattern. We hope to add it to the SDK directly in future. 🙂
