### ISSUE TITLE
Env PATH missing

### ISSUE THREAD

**Issue by calclavia** [modelcontextprotocol/typescript-sdk#92]
**Describe the bug**
There's a bug that happens when we have to use Stdiotransport and pass in a local node process:
```
 {
  command: "node",
  args: [
	  "./mcp-server-browserbase/stagehand/dist/index.js",
  ],
  env: {
	  BROWSERBASE_PROJECT_ID: process.env.BROWSERBASE_PROJECT_ID,
	  BROWSERBASE_API_KEY: process.env.BROWSERBASE_API_KEY,
	  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  },
},
```
This will lead to the node process spawning with an error and it's caused by the `env` object.

To fix, we must add the PATH variable to `env`.
```
 {
  command: "node",
  args: [
	  "./mcp-server-browserbase/stagehand/dist/index.js",
  ],
  env: {
	  BROWSERBASE_PROJECT_ID: process.env.BROWSERBASE_PROJECT_ID,
	  BROWSERBASE_API_KEY: process.env.BROWSERBASE_API_KEY,
	  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
	  PATH: process.env.PATH as string,
  },
},
```

It'll be good if the StdioTransport Client patched the `PATH` by default to avoid gotchas.

See: https://maxschmitt.me/posts/error-spawn-node-enoent-node-js-child-process

**Comment by jspahrsummers** [comment]
This is by design, as otherwise there would be no way for callers to strip out our default keys. You can combine your overrides with [`getDefaultEnvironment()`](https://github.com/modelcontextprotocol/typescript-sdk/blob/22370be34038401977e4d12ac10cd06d85ddd025/src/client/stdio.ts#L55-L76) to include `PATH` and others here.

**Comment by calclavia** [comment]
@jspahrsummers that's fair. Maybe we could add this to the docs of the typing? I can make a PR if you think that's helpful.

**Comment by jspahrsummers** [comment]
Yes, that would be great—thank you!

**Comment by nbbaier** [comment]
@calclavia, I wanted to follow up on this - what's the way to make sure the path is present if you're reading `env` from a json config?
