### ISSUE TITLE
SSEClientTransport ReferenceError: EventSource is not defined

### ISSUE THREAD

**Issue by MrKiven** [modelcontextprotocol/typescript-sdk#96]
**Describe the bug**
I use `SSEClientTransport` to create a client,  but it raise an error like this: 
```
 file:///xxx/file-tools-server/node_modules/@modelcontextprotocol/sdk/dist/client/sse.js:17
            this._eventSource = new EventSource(this._url.href);
```

**To Reproduce**
1. create node server 
2. install @modelcontextprotocol/sdk
3. copy `client.ts` at README.md, modify the transport to `SSEClientTransport`
4. npm run build
5. node build/client.js

**Expected behavior**
success connect server and get tools/resources

**Logs**
NO

**Additional context**
NO

**Comment by jspahrsummers** [comment]
This is expected—see the docstring here: https://github.com/modelcontextprotocol/typescript-sdk/blob/2a3cab20e6a9feaac20c12a341dad54357fbb520/src/client/sse.ts#L8
